language: python

# Download jadx decompiler
before_script:
  - wget https://github.com/skylot/jadx/releases/download/v0.6.1/jadx-0.6.1.zip -O /tmp/jadx-0.6.1.zip
  - unzip /tmp/jadx-0.6.1.zip -d jadx-0.6.1
  - export PATH=$PATH:$PWD/jadx-0.6.1/bin

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
# command to install dependencies
install:
  - "pip install -r test-requirements.txt"
  # sphinxcontrib-programoutput >= 0.9 is not supported by python 2.6, 3.2 and 3.3
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install sphinxcontrib-programoutput==0.8; else pip install sphinxcontrib-programoutput; fi
  - "pip install ."
# command to run tests
script:
  - nosetests --with-coverage
  - python setup.py build_sphinx

notifications:
  email:
    recipients:
      - desnos@t0t0.fr
    on_success: always
    on_failure: always

after_success:
  - codecov
