language: python

addons:
  apt:
    packages:
      - openjdk-8-jre-headless

# Download jadx decompiler
before-script:
  - wget https://github.com/skylot/jadx/releases/download/v0.6.1/jadx-0.6.1.zip -O /tmp/jadx-0.6.1.zip
  - unzip /tmp/jadx-0.6.1.zip
  - export PATH=$PATH:$PWD/bin

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
# command to install dependencies
install:
  - pip install nose codecov coverage
  - "pip install ."
  - "pip install -r requirements.txt"
  - pip install codecov
# command to run tests
script:
  - nosetest -v --with-coverage

notifications:
  email:
    recipients:
      - desnos@t0t0.fr
    on_success: always
    on_failure: always

after_success:
  - codecov
